services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - transcription-bot
        - ghcr.io/craft-concept/transcription-bot
    image: "transcription-bot"
    volumes:
      - ./storage:/app/storage
    env_file: "compose.env"

  whisper:
    image: "ghcr.io/craft-concept/whisper.cpp"
    volumes:
      - models:/models
    command: ["./server", "-m", "/models/large-v3-turbo-q5_0.bin"]

volumes:
  models:
    external: true
