services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "transcription-bot"
    volumes:
      - ./storage:/app/storage
      - models:/models
    env_file: "compose.env"
    command: "npm run start"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
volumes:
  models:
    external: true
