services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - transcription-bot
        - ghcr.io/craft-concept/transcription-bot
    image: "transcription-bot"
    volumes:
      - ./storage:/app/storage
    env_file: "compose.env"

  whisper:
    image: "ghcr.io/craft-concept/whisper.cpp:cuda"
    volumes:
      - models:/models
    command: ["./server", "-m", "/models/large-v3-turbo-q5_0.bin"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  models:
    external: true
